language: php
php:
  - 5.3
  - 5.4
before_script:
  - ./bin/initialize-dependencies.sh submodules
  - sh -c ./bin/initialize-ci.sh 1.0rc6
script: phpunit test/
notifications:
  email:
    - alessandro.nadalin@gmail.com
    - ing.davidino@gmail.com
